applicationName: Sample App

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: root
  url: jdbc:mysql://127.0.0.1:3306/db_notes
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
